### PR TITLE
Implementing right to left text support

### PR DESCRIPTION
**Pull request by sgrieve**
This is a work in progress PR to manage the work required to support right to left text, e.g. Arabic within ATF files. The complete scope of this still needs to be defined.

Initial work has identified that we can change the text direction by editing the `ComponentOrientation` within the constructor of `AtfEditArea`. however, this results in strange behaviour, where the first character of a line (in left to right mode) is moved to the far right of the line in right to left mode. This also happens when we use the keyboard shortcut documented in #297, which appears to do the same thing.

### CODE REVIEW

**Comment by sgrieve** [comment]
Upon further exploration it appears that the issue is not with the first or last character of a line, but with punctuation marks at the start or end of lines. See these examples:

screen shot 2018-03-20 at 15 20 51
screen shot 2018-03-20 at 15 21 06
screen shot 2018-03-20 at 15 23 02
screen shot 2018-03-20 at 15 23 17
screen shot 2018-03-20 at 15 23 52
screen shot 2018-03-20 at 15 24 32

I do not understand the exact set of characters that are moved around, and can't find any documentation about it. The next step is to speak with Arabic speakers and users to understand the scale of the impact this will have on maintaining correctly formatted ATF files.

**Comment by ageorgou** [comment]
I'm seeing something similar with punctuation when changing the text direction of HTML pages. Perhaps this is an issue with what constitutes a "word" in a right-to-left language for the purposes of display?

**Comment by ageorgou** [comment]
It seems this may be the expected behaviour. A (hopefully) useful description of why it happens and how to work around it: https://www.w3.org/International/articles/inline-bidi-markup/uba-basics

**Comment by sgrieve** [comment]
The initial plan is to preserve left to right text for the headers and transliterations and lemmatizations. Then switch to right to left for the translations in Arabic. There are language codes in the atf format to signify a change of language.

We are assuming a single atf header per file so there will be one switch from left to right to right to left per file.

Next step is to understand how to do the switch at a specified point in the file.

**Comment by sgrieve** [comment]
The MWE added in the last commit shows how to interleave text directions on a line by line basis.

**Comment by sgrieve** [comment]
The right to left text is mostly working now. One issue is that if the language code is changed from `ar`, the translation will not switch back to left justified.

**Comment by sgrieve** [comment]
Based on #315 we will need to add support for:

- [x] ar = Arabic
- [ ] fa = Farsi/modern Persian
- [ ] ku = Kurdish

and for:

- [ ] labeled translations
- [ ] unitary translations

**Comment by sgrieve** [comment]
This branch has been merged into #318 so this PR is not closed.

**Pull request closed without merging**
