### PR TITLE
Added links to Nammu's JAR release and JVM download.

### PR DESCRIPTION
**Pull request by raquel-ucl**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I don't think users need JDK (developer kit) the Java runtime environment JRE should be sufficient.
i.e.  http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by raquel-ucl** [comment]
Sure, the link points to the JRE, but I'll change the text accordingly.

**Comment by jenshnielsen** [comment]
I think the link points to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html ?

**Comment by raquel-ucl** [comment]
Oh yes :)

**Comment by raquel-ucl** [comment]
Done now.

**Pull request merged**
